spring:
  datasource:
    url: jdbc:mysql://localhost:3306/image-upload
    username: root
    password: a1b2c3!!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
    open-in-view: false


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # SMTP
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: ture
          auth: ture

jwt:
  header: ${HEADER:Authorize}
  prefix : ${PREFIX:Bearer}
  secret-key: ${JWT_SECRET_KEY:dffddefcerdfrefervrevfvvfffgbfgfgdb}
  accessExp: ${JWT_ACCESS_EXP:12000}
  refreshExp: ${JWT_REFRESH_EXP:24000}

logging:
  level:
    com.example : DEBUG
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
cloud:
  aws:
    s3:
      bucket: ${BUCKET_NAME}
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${ACCESS_KEY}
      secretKey: ${SECRET_KEY}